namespace CPBourg.NextGenGui.Views
{
    /// <summary>
    /// STFO-specific copy kept separate from the shared shell catalog so the
    /// configuration wizard can be reviewed and extended as one unit.
    /// </summary>
    public static partial class LocalizationManager
    {
        private static void AddStfoTranslations()
        {
            AddTo("fr",
                "Menu", "Menu", "Stitching", "Piqûre", "Folding", "Pliage",
                "Trimming", "Massicotage", "Conveyor", "Convoyeur",
                "1. Menu", "1. Menu", "2. Stitching", "2. Piqûre",
                "3. Folding", "3. Pliage", "4. Trimming", "4. Massicotage",
                "5. Conveyor", "5. Convoyeur",
                "Overview and live machine preview.", "Vue d’ensemble et aperçu en direct de la machine.",
                "Configure stitching for this job.", "Configurez la piqûre pour ce travail.",
                "Configure folding for this job.", "Configurez le pliage pour ce travail.",
                "Configure trimming for this job.", "Configurez le massicotage pour ce travail.",
                "Configure the conveyor / output for this job.", "Configurez le convoyeur / la sortie pour ce travail.",
                "Live Preview", "Aperçu en direct", "Status: ", "État : ",
                "Machine: ", "Machine : ", "Job: ", "Travail : ",
                "No job loaded", "Aucun travail chargé", "{0} pages", "{0} pages",
                "Back", "Retour", "Back: {0}", "Retour : {0}",
                "Next: {0}", "Suivant : {0}",
                "Select a configuration step to reset its settings.", "Sélectionnez une étape de configuration à réinitialiser.",
                "{0} settings reset to defaults. Select Save to keep them.", "Les paramètres de {0} ont été réinitialisés. Sélectionnez Enregistrer pour les conserver.",
                "Select a configuration step to save its settings.", "Sélectionnez une étape de configuration à enregistrer.",
                "{0} configuration saved.", "Configuration de {0} enregistrée.",
                "Paper Size (W x L)", "Format papier (L x H)", "Stitch Mode", "Mode de piqûre",
                "Spacing", "Espacement", "Horizontal Offset", "Décalage horizontal",
                "Vertical Offset", "Décalage vertical", "Stitching Parameters", "Paramètres de piqûre",
                "Paper Width (W)", "Largeur papier (L)", "Paper Length (L)", "Longueur papier (H)",
                "Saddle", "À cheval", "Top", "En tête", "Right Corner", "Coin droit",
                "Left Corner", "Coin gauche", "None", "Aucune",
                "Spacing Between Stitches", "Espacement entre les agrafes",
                "Horizontal Offset Stitch", "Décalage horizontal des agrafes",
                "(Left -/ Right +)", "(Gauche - / Droite +)",
                "Vertical Offset Stitch", "Décalage vertical des agrafes",
                "(Front - / Rear +)", "(Avant - / Arrière +)", "No stitching", "Piqûre désactivée",
                "Set Paper Width", "Régler la largeur du papier",
                "Paper width ({0})", "Largeur du papier ({0})",
                "Enter the sheet width used by the stitching job.", "Saisissez la largeur de feuille utilisée pour la piqûre.",
                "Set Paper Length", "Régler la longueur du papier",
                "Paper length ({0})", "Longueur du papier ({0})",
                "Enter the sheet length used by the stitching job.", "Saisissez la longueur de feuille utilisée pour la piqûre.",
                "Set Stitch Spacing", "Régler l’espacement des agrafes",
                "Spacing between stitches ({0})", "Espacement entre les agrafes ({0})",
                "Enter the distance between stitch positions.", "Saisissez la distance entre les positions d’agrafage.",
                "Set Horizontal Offset", "Régler le décalage horizontal",
                "Horizontal offset ({0})", "Décalage horizontal ({0})",
                "Use a negative value for left or a positive value for right.", "Utilisez une valeur négative à gauche ou positive à droite.",
                "Set Vertical Offset", "Régler le décalage vertical",
                "Vertical offset ({0})", "Décalage vertical ({0})",
                "Use a negative value for front or a positive value for rear.", "Utilisez une valeur négative vers l’avant ou positive vers l’arrière.",
                "Paper width", "Largeur du papier", "Paper length", "Longueur du papier",
                "Stitch spacing", "Espacement des agrafes", "Horizontal offset", "Décalage horizontal",
                "Vertical offset", "Décalage vertical", "{0} updated to {1} {2}.", "{0} mis à jour à {1} {2}.",
                "Folding Settings", "Paramètres de pliage", "Fold Function:", "Fonction de pliage :",
                "Fold Position", "Position du pli", "Backward (-)", "Arrière (-)",
                "Forward (+)", "Avant (+)", "Adjust fold...", "Régler le pli…",
                "Pressure Mode", "Mode de pression", "Auto", "Auto", "Default", "Par défaut",
                "Manual", "Manuel", "Less pressure", "Moins de pression",
                "More pressure", "Plus de pression",
                "Auto mode sets the clamp pressure automatically.", "Le mode Auto règle automatiquement la pression de serrage.",
                "Fold offset (from center)", "Décalage du pli (depuis le centre)",
                "Fold direction", "Sens du pli", "Folding disabled", "Pliage désactivé",
                "Set Fold Position", "Régler la position du pli",
                "Fold position ({0})", "Position du pli ({0})",
                "Enter a value from {0} (backward) to {1} (forward).", "Saisissez une valeur de {0} (arrière) à {1} (avant).",
                "Fold position", "Position du pli",
                "Trimming Settings", "Paramètres de massicotage", "Trim Function:", "Fonction de massicotage :",
                "Final Booklet Length", "Longueur finale de la brochure",
                "Enter desired final length", "Saisir la longueur finale souhaitée",
                "Clamp Conveyor Height", "Hauteur du convoyeur de serrage",
                "Automatic", "Automatique", "Maximum", "Maximum", "Minimum", "Minimum",
                "Chip Blower", "Soufflerie de rognures", "On", "Marche", "Off", "Arrêt",
                "Evacuates trim chips", "Évacue les rognures",
                "Set Final Booklet Length", "Régler la longueur finale de la brochure",
                "Final booklet length ({0})", "Longueur finale de la brochure ({0})",
                "Enter the desired finished length from {0} to {1}.", "Saisissez la longueur finie souhaitée de {0} à {1}.",
                "Final booklet length", "Longueur finale de la brochure",
                "Conveyor Settings", "Paramètres du convoyeur",
                "Booklet Spacing", "Espacement des brochures", "Booklet Offset", "Décalage des brochures",
                "Conveyor Full Detection", "Détection de convoyeur plein",
                "1 = small space, 29 = long space, 30 = continuous advance", "1 = petit espace, 29 = grand espace, 30 = avance continue",
                "Set Booklet Spacing", "Régler l’espacement des brochures",
                "Booklet spacing", "Espacement des brochures",
                "Enter the output conveyor advance from 1 to 30.", "Saisissez l’avance du convoyeur de sortie de 1 à 30.",
                "Set Booklet Offset", "Régler le décalage des brochures",
                "Booklet offset", "Décalage des brochures",
                "Enter how often a booklet should be offset, from 1 to 30.", "Saisissez la fréquence de décalage des brochures, de 1 à 30.",
                "Enter a whole number from 1 to 30.", "Saisissez un nombre entier de 1 à 30.",
                "{0} updated to {1}.", "{0} mis à jour à {1}.",
                "Use +/- for direction and . for fractional values.", "Utilisez +/- pour le sens et . pour les décimales.",
                "Use the decimal key for fractional values.", "Utilisez la touche décimale pour les valeurs fractionnaires.",
                "Enter a value from {0} to {1}.", "Saisissez une valeur de {0} à {1}.",
                "Enter Value", "Saisir une valeur", "Enter a numeric value.", "Saisissez une valeur numérique.",
                "Enter at least one digit.", "Saisissez au moins un chiffre.", "Clear", "Effacer");

            AddTo("nl",
                "Menu", "Menu", "Stitching", "Nieten", "Folding", "Vouwen", "Trimming", "Snijden", "Conveyor", "Transportband",
                "1. Menu", "1. Menu", "2. Stitching", "2. Nieten", "3. Folding", "3. Vouwen", "4. Trimming", "4. Snijden", "5. Conveyor", "5. Transportband",
                "Overview and live machine preview.", "Overzicht en live machineweergave.",
                "Configure stitching for this job.", "Configureer het nieten voor deze taak.",
                "Configure folding for this job.", "Configureer het vouwen voor deze taak.",
                "Configure trimming for this job.", "Configureer het snijden voor deze taak.",
                "Configure the conveyor / output for this job.", "Configureer de transportband / uitvoer voor deze taak.",
                "Live Preview", "Live voorbeeld", "Status: ", "Status: ", "Machine: ", "Machine: ", "Job: ", "Taak: ",
                "No job loaded", "Geen taak geladen", "{0} pages", "{0} pagina’s",
                "Back", "Terug", "Back: {0}", "Terug: {0}", "Next: {0}", "Volgende: {0}",
                "Select a configuration step to reset its settings.", "Selecteer een configuratiestap om de instellingen te herstellen.",
                "{0} settings reset to defaults. Select Save to keep them.", "Instellingen voor {0} zijn hersteld. Selecteer Opslaan om ze te behouden.",
                "Select a configuration step to save its settings.", "Selecteer een configuratiestap om de instellingen op te slaan.",
                "{0} configuration saved.", "Configuratie voor {0} opgeslagen.",
                "Paper Size (W x L)", "Papierformaat (B x L)", "Stitch Mode", "Nietmodus", "Spacing", "Afstand",
                "Horizontal Offset", "Horizontale verschuiving", "Vertical Offset", "Verticale verschuiving",
                "Stitching Parameters", "Nietparameters", "Paper Width (W)", "Papierbreedte (B)",
                "Paper Length (L)", "Papierlengte (L)", "Saddle", "Rugnieten", "Top", "Boven",
                "Right Corner", "Rechterhoek", "Left Corner", "Linkerhoek", "None", "Geen",
                "Spacing Between Stitches", "Afstand tussen nietjes",
                "Horizontal Offset Stitch", "Horizontale nietverschuiving", "(Left -/ Right +)", "(Links - / Rechts +)",
                "Vertical Offset Stitch", "Verticale nietverschuiving", "(Front - / Rear +)", "(Voor - / Achter +)",
                "No stitching", "Nieten uitgeschakeld",
                "Set Paper Width", "Papierbreedte instellen", "Paper width ({0})", "Papierbreedte ({0})",
                "Enter the sheet width used by the stitching job.", "Voer de papierbreedte voor deze niettaak in.",
                "Set Paper Length", "Papierlengte instellen", "Paper length ({0})", "Papierlengte ({0})",
                "Enter the sheet length used by the stitching job.", "Voer de papierlengte voor deze niettaak in.",
                "Set Stitch Spacing", "Nietafstand instellen", "Spacing between stitches ({0})", "Afstand tussen nietjes ({0})",
                "Enter the distance between stitch positions.", "Voer de afstand tussen nietposities in.",
                "Set Horizontal Offset", "Horizontale verschuiving instellen", "Horizontal offset ({0})", "Horizontale verschuiving ({0})",
                "Use a negative value for left or a positive value for right.", "Gebruik een negatieve waarde voor links en een positieve voor rechts.",
                "Set Vertical Offset", "Verticale verschuiving instellen", "Vertical offset ({0})", "Verticale verschuiving ({0})",
                "Use a negative value for front or a positive value for rear.", "Gebruik een negatieve waarde voor voor en een positieve voor achter.",
                "Paper width", "Papierbreedte", "Paper length", "Papierlengte", "Stitch spacing", "Nietafstand",
                "Horizontal offset", "Horizontale verschuiving", "Vertical offset", "Verticale verschuiving",
                "{0} updated to {1} {2}.", "{0} bijgewerkt naar {1} {2}.",
                "Folding Settings", "Vouwinstellingen", "Fold Function:", "Vouwfunctie:", "Fold Position", "Vouwpositie",
                "Backward (-)", "Achteruit (-)", "Forward (+)", "Vooruit (+)", "Adjust fold...", "Vouw aanpassen…",
                "Pressure Mode", "Drukmodus", "Auto", "Auto", "Default", "Standaard", "Manual", "Handmatig",
                "Less pressure", "Minder druk", "More pressure", "Meer druk",
                "Auto mode sets the clamp pressure automatically.", "De automatische modus stelt de klemdruk automatisch in.",
                "Fold offset (from center)", "Vouwverschuiving (vanaf midden)", "Fold direction", "Vouwrichting",
                "Folding disabled", "Vouwen uitgeschakeld", "Set Fold Position", "Vouwpositie instellen",
                "Fold position ({0})", "Vouwpositie ({0})",
                "Enter a value from {0} (backward) to {1} (forward).", "Voer een waarde in van {0} (achteruit) tot {1} (vooruit).",
                "Fold position", "Vouwpositie",
                "Trimming Settings", "Snij-instellingen", "Trim Function:", "Snijfunctie:",
                "Final Booklet Length", "Uiteindelijke boeklengte", "Enter desired final length", "Voer de gewenste eindlengte in",
                "Clamp Conveyor Height", "Hoogte klemtransportband", "Automatic", "Automatisch",
                "Maximum", "Maximum", "Minimum", "Minimum", "Chip Blower", "Snijafvalblazer",
                "On", "Aan", "Off", "Uit", "Evacuates trim chips", "Voert snijafval af",
                "Set Final Booklet Length", "Uiteindelijke boeklengte instellen",
                "Final booklet length ({0})", "Uiteindelijke boeklengte ({0})",
                "Enter the desired finished length from {0} to {1}.", "Voer de gewenste eindlengte van {0} tot {1} in.",
                "Final booklet length", "Uiteindelijke boeklengte",
                "Conveyor Settings", "Transportbandinstellingen", "Booklet Spacing", "Boekafstand",
                "Booklet Offset", "Boekverschuiving", "Conveyor Full Detection", "Detectie volle transportband",
                "1 = small space, 29 = long space, 30 = continuous advance", "1 = kleine afstand, 29 = grote afstand, 30 = continu transport",
                "Set Booklet Spacing", "Boekafstand instellen", "Booklet spacing", "Boekafstand",
                "Enter the output conveyor advance from 1 to 30.", "Voer de uitvoertransportstap van 1 tot 30 in.",
                "Set Booklet Offset", "Boekverschuiving instellen", "Booklet offset", "Boekverschuiving",
                "Enter how often a booklet should be offset, from 1 to 30.", "Voer in hoe vaak een boek moet verschuiven, van 1 tot 30.",
                "Enter a whole number from 1 to 30.", "Voer een geheel getal van 1 tot 30 in.",
                "{0} updated to {1}.", "{0} bijgewerkt naar {1}.",
                "Use +/- for direction and . for fractional values.", "Gebruik +/- voor de richting en . voor decimalen.",
                "Use the decimal key for fractional values.", "Gebruik de decimale toets voor breukwaarden.",
                "Enter a value from {0} to {1}.", "Voer een waarde in van {0} tot {1}.",
                "Enter Value", "Waarde invoeren", "Enter a numeric value.", "Voer een numerieke waarde in.",
                "Enter at least one digit.", "Voer minstens één cijfer in.", "Clear", "Wissen");

            AddTo("de",
                "Menu", "Menü", "Stitching", "Heften", "Folding", "Falzen", "Trimming", "Schneiden", "Conveyor", "Auslage",
                "1. Menu", "1. Menü", "2. Stitching", "2. Heften", "3. Folding", "3. Falzen", "4. Trimming", "4. Schneiden", "5. Conveyor", "5. Auslage",
                "Overview and live machine preview.", "Übersicht und Live-Maschinenansicht.",
                "Configure stitching for this job.", "Heftung für diesen Auftrag konfigurieren.",
                "Configure folding for this job.", "Falzung für diesen Auftrag konfigurieren.",
                "Configure trimming for this job.", "Beschnitt für diesen Auftrag konfigurieren.",
                "Configure the conveyor / output for this job.", "Auslage / Ausgabe für diesen Auftrag konfigurieren.",
                "Live Preview", "Live-Vorschau", "Status: ", "Status: ", "Machine: ", "Maschine: ", "Job: ", "Auftrag: ",
                "No job loaded", "Kein Auftrag geladen", "{0} pages", "{0} Seiten",
                "Back", "Zurück", "Back: {0}", "Zurück: {0}", "Next: {0}", "Weiter: {0}",
                "Select a configuration step to reset its settings.", "Wählen Sie einen Konfigurationsschritt zum Zurücksetzen.",
                "{0} settings reset to defaults. Select Save to keep them.", "{0}-Einstellungen zurückgesetzt. Wählen Sie Speichern, um sie zu behalten.",
                "Select a configuration step to save its settings.", "Wählen Sie einen Konfigurationsschritt zum Speichern.",
                "{0} configuration saved.", "{0}-Konfiguration gespeichert.",
                "Paper Size (W x L)", "Papierformat (B x L)", "Stitch Mode", "Heftmodus", "Spacing", "Abstand",
                "Horizontal Offset", "Horizontalversatz", "Vertical Offset", "Vertikalversatz",
                "Stitching Parameters", "Heftparameter", "Paper Width (W)", "Papierbreite (B)", "Paper Length (L)", "Papierlänge (L)",
                "Saddle", "Rückstich", "Top", "Oben", "Right Corner", "Rechte Ecke", "Left Corner", "Linke Ecke", "None", "Keine",
                "Spacing Between Stitches", "Abstand zwischen Heftklammern",
                "Horizontal Offset Stitch", "Horizontaler Heftversatz", "(Left -/ Right +)", "(Links - / Rechts +)",
                "Vertical Offset Stitch", "Vertikaler Heftversatz", "(Front - / Rear +)", "(Vorne - / Hinten +)",
                "No stitching", "Heftung deaktiviert",
                "Set Paper Width", "Papierbreite einstellen", "Paper width ({0})", "Papierbreite ({0})",
                "Enter the sheet width used by the stitching job.", "Geben Sie die Blattbreite für den Heftauftrag ein.",
                "Set Paper Length", "Papierlänge einstellen", "Paper length ({0})", "Papierlänge ({0})",
                "Enter the sheet length used by the stitching job.", "Geben Sie die Blattlänge für den Heftauftrag ein.",
                "Set Stitch Spacing", "Heftabstand einstellen", "Spacing between stitches ({0})", "Abstand zwischen Heftklammern ({0})",
                "Enter the distance between stitch positions.", "Geben Sie den Abstand zwischen den Heftpositionen ein.",
                "Set Horizontal Offset", "Horizontalversatz einstellen", "Horizontal offset ({0})", "Horizontalversatz ({0})",
                "Use a negative value for left or a positive value for right.", "Verwenden Sie einen negativen Wert für links und einen positiven für rechts.",
                "Set Vertical Offset", "Vertikalversatz einstellen", "Vertical offset ({0})", "Vertikalversatz ({0})",
                "Use a negative value for front or a positive value for rear.", "Verwenden Sie einen negativen Wert für vorne und einen positiven für hinten.",
                "Paper width", "Papierbreite", "Paper length", "Papierlänge", "Stitch spacing", "Heftabstand",
                "Horizontal offset", "Horizontalversatz", "Vertical offset", "Vertikalversatz",
                "{0} updated to {1} {2}.", "{0} auf {1} {2} aktualisiert.",
                "Folding Settings", "Falzeinstellungen", "Fold Function:", "Falzfunktion:", "Fold Position", "Falzposition",
                "Backward (-)", "Rückwärts (-)", "Forward (+)", "Vorwärts (+)", "Adjust fold...", "Falz einstellen…",
                "Pressure Mode", "Druckmodus", "Auto", "Auto", "Default", "Standard", "Manual", "Manuell",
                "Less pressure", "Weniger Druck", "More pressure", "Mehr Druck",
                "Auto mode sets the clamp pressure automatically.", "Im Automatikmodus wird der Klemmdruck automatisch eingestellt.",
                "Fold offset (from center)", "Falzversatz (ab Mitte)", "Fold direction", "Falzrichtung",
                "Folding disabled", "Falzen deaktiviert", "Set Fold Position", "Falzposition einstellen",
                "Fold position ({0})", "Falzposition ({0})",
                "Enter a value from {0} (backward) to {1} (forward).", "Geben Sie einen Wert von {0} (rückwärts) bis {1} (vorwärts) ein.",
                "Fold position", "Falzposition",
                "Trimming Settings", "Schneideinstellungen", "Trim Function:", "Schneidefunktion:",
                "Final Booklet Length", "Endlänge der Broschüre", "Enter desired final length", "Gewünschte Endlänge eingeben",
                "Clamp Conveyor Height", "Höhe des Klemmförderers", "Automatic", "Automatisch",
                "Maximum", "Maximum", "Minimum", "Minimum", "Chip Blower", "Schnitzelgebläse",
                "On", "Ein", "Off", "Aus", "Evacuates trim chips", "Führt Schnittabfälle ab",
                "Set Final Booklet Length", "Endlänge der Broschüre einstellen",
                "Final booklet length ({0})", "Endlänge der Broschüre ({0})",
                "Enter the desired finished length from {0} to {1}.", "Geben Sie die gewünschte Endlänge von {0} bis {1} ein.",
                "Final booklet length", "Endlänge der Broschüre",
                "Conveyor Settings", "Auslageeinstellungen", "Booklet Spacing", "Broschürenabstand",
                "Booklet Offset", "Broschürenversatz", "Conveyor Full Detection", "Erkennung volle Auslage",
                "1 = small space, 29 = long space, 30 = continuous advance", "1 = kleiner Abstand, 29 = großer Abstand, 30 = kontinuierlicher Vorschub",
                "Set Booklet Spacing", "Broschürenabstand einstellen", "Booklet spacing", "Broschürenabstand",
                "Enter the output conveyor advance from 1 to 30.", "Geben Sie den Auslagevorschub von 1 bis 30 ein.",
                "Set Booklet Offset", "Broschürenversatz einstellen", "Booklet offset", "Broschürenversatz",
                "Enter how often a booklet should be offset, from 1 to 30.", "Geben Sie ein, wie oft eine Broschüre versetzt werden soll, von 1 bis 30.",
                "Enter a whole number from 1 to 30.", "Geben Sie eine ganze Zahl von 1 bis 30 ein.",
                "{0} updated to {1}.", "{0} auf {1} aktualisiert.",
                "Use +/- for direction and . for fractional values.", "Verwenden Sie +/- für die Richtung und . für Dezimalwerte.",
                "Use the decimal key for fractional values.", "Verwenden Sie die Dezimaltaste für Dezimalwerte.",
                "Enter a value from {0} to {1}.", "Geben Sie einen Wert von {0} bis {1} ein.",
                "Enter Value", "Wert eingeben", "Enter a numeric value.", "Geben Sie einen Zahlenwert ein.",
                "Enter at least one digit.", "Geben Sie mindestens eine Ziffer ein.", "Clear", "Löschen");

            AddTo("es",
                "Menu", "Menú", "Stitching", "Grapado", "Folding", "Plegado", "Trimming", "Corte", "Conveyor", "Transportador",
                "1. Menu", "1. Menú", "2. Stitching", "2. Grapado", "3. Folding", "3. Plegado", "4. Trimming", "4. Corte", "5. Conveyor", "5. Transportador",
                "Overview and live machine preview.", "Vista general y vista previa de la máquina en directo.",
                "Configure stitching for this job.", "Configure el grapado para este trabajo.",
                "Configure folding for this job.", "Configure el plegado para este trabajo.",
                "Configure trimming for this job.", "Configure el corte para este trabajo.",
                "Configure the conveyor / output for this job.", "Configure el transportador / la salida para este trabajo.",
                "Live Preview", "Vista previa", "Status: ", "Estado: ", "Machine: ", "Máquina: ", "Job: ", "Trabajo: ",
                "No job loaded", "No hay trabajo cargado", "{0} pages", "{0} páginas",
                "Back", "Atrás", "Back: {0}", "Atrás: {0}", "Next: {0}", "Siguiente: {0}",
                "Select a configuration step to reset its settings.", "Seleccione un paso de configuración para restablecerlo.",
                "{0} settings reset to defaults. Select Save to keep them.", "Los ajustes de {0} se restablecieron. Seleccione Guardar para conservarlos.",
                "Select a configuration step to save its settings.", "Seleccione un paso de configuración para guardar sus ajustes.",
                "{0} configuration saved.", "Configuración de {0} guardada.",
                "Paper Size (W x L)", "Tamaño de papel (An. x L)", "Stitch Mode", "Modo de grapado", "Spacing", "Separación",
                "Horizontal Offset", "Desplazamiento horizontal", "Vertical Offset", "Desplazamiento vertical",
                "Stitching Parameters", "Parámetros de grapado", "Paper Width (W)", "Ancho del papel (An.)", "Paper Length (L)", "Longitud del papel (L)",
                "Saddle", "A caballete", "Top", "Superior", "Right Corner", "Esquina derecha", "Left Corner", "Esquina izquierda", "None", "Ninguno",
                "Spacing Between Stitches", "Separación entre grapas", "Horizontal Offset Stitch", "Desplazamiento horizontal de grapas",
                "(Left -/ Right +)", "(Izquierda - / Derecha +)", "Vertical Offset Stitch", "Desplazamiento vertical de grapas",
                "(Front - / Rear +)", "(Frente - / Atrás +)", "No stitching", "Grapado desactivado",
                "Set Paper Width", "Definir ancho del papel", "Paper width ({0})", "Ancho del papel ({0})",
                "Enter the sheet width used by the stitching job.", "Introduzca el ancho de hoja usado para el grapado.",
                "Set Paper Length", "Definir longitud del papel", "Paper length ({0})", "Longitud del papel ({0})",
                "Enter the sheet length used by the stitching job.", "Introduzca la longitud de hoja usada para el grapado.",
                "Set Stitch Spacing", "Definir separación de grapas", "Spacing between stitches ({0})", "Separación entre grapas ({0})",
                "Enter the distance between stitch positions.", "Introduzca la distancia entre las posiciones de grapado.",
                "Set Horizontal Offset", "Definir desplazamiento horizontal", "Horizontal offset ({0})", "Desplazamiento horizontal ({0})",
                "Use a negative value for left or a positive value for right.", "Use un valor negativo para izquierda o positivo para derecha.",
                "Set Vertical Offset", "Definir desplazamiento vertical", "Vertical offset ({0})", "Desplazamiento vertical ({0})",
                "Use a negative value for front or a positive value for rear.", "Use un valor negativo para el frente o positivo para atrás.",
                "Paper width", "Ancho del papel", "Paper length", "Longitud del papel", "Stitch spacing", "Separación de grapas",
                "Horizontal offset", "Desplazamiento horizontal", "Vertical offset", "Desplazamiento vertical",
                "{0} updated to {1} {2}.", "{0} actualizado a {1} {2}.",
                "Folding Settings", "Ajustes de plegado", "Fold Function:", "Función de plegado:", "Fold Position", "Posición del pliegue",
                "Backward (-)", "Atrás (-)", "Forward (+)", "Adelante (+)", "Adjust fold...", "Ajustar pliegue…",
                "Pressure Mode", "Modo de presión", "Auto", "Auto", "Default", "Predeterminado", "Manual", "Manual",
                "Less pressure", "Menos presión", "More pressure", "Más presión",
                "Auto mode sets the clamp pressure automatically.", "El modo automático ajusta la presión de sujeción.",
                "Fold offset (from center)", "Desplazamiento del pliegue (desde el centro)", "Fold direction", "Dirección del pliegue",
                "Folding disabled", "Plegado desactivado", "Set Fold Position", "Definir posición del pliegue",
                "Fold position ({0})", "Posición del pliegue ({0})",
                "Enter a value from {0} (backward) to {1} (forward).", "Introduzca un valor de {0} (atrás) a {1} (adelante).",
                "Fold position", "Posición del pliegue",
                "Trimming Settings", "Ajustes de corte", "Trim Function:", "Función de corte:",
                "Final Booklet Length", "Longitud final del folleto", "Enter desired final length", "Introduzca la longitud final deseada",
                "Clamp Conveyor Height", "Altura del transportador de sujeción", "Automatic", "Automático",
                "Maximum", "Máximo", "Minimum", "Mínimo", "Chip Blower", "Soplador de recortes",
                "On", "Encendido", "Off", "Apagado", "Evacuates trim chips", "Evacua los recortes",
                "Set Final Booklet Length", "Definir longitud final del folleto",
                "Final booklet length ({0})", "Longitud final del folleto ({0})",
                "Enter the desired finished length from {0} to {1}.", "Introduzca la longitud final deseada de {0} a {1}.",
                "Final booklet length", "Longitud final del folleto",
                "Conveyor Settings", "Ajustes del transportador", "Booklet Spacing", "Separación de folletos",
                "Booklet Offset", "Desplazamiento de folletos", "Conveyor Full Detection", "Detección de transportador lleno",
                "1 = small space, 29 = long space, 30 = continuous advance", "1 = espacio pequeño, 29 = espacio grande, 30 = avance continuo",
                "Set Booklet Spacing", "Definir separación de folletos", "Booklet spacing", "Separación de folletos",
                "Enter the output conveyor advance from 1 to 30.", "Introduzca el avance del transportador de salida de 1 a 30.",
                "Set Booklet Offset", "Definir desplazamiento de folletos", "Booklet offset", "Desplazamiento de folletos",
                "Enter how often a booklet should be offset, from 1 to 30.", "Introduzca cada cuántos folletos debe aplicarse el desplazamiento, de 1 a 30.",
                "Enter a whole number from 1 to 30.", "Introduzca un número entero de 1 a 30.",
                "{0} updated to {1}.", "{0} actualizado a {1}.",
                "Use +/- for direction and . for fractional values.", "Use +/- para la dirección y . para los decimales.",
                "Use the decimal key for fractional values.", "Use la tecla decimal para valores fraccionarios.",
                "Enter a value from {0} to {1}.", "Introduzca un valor de {0} a {1}.",
                "Enter Value", "Introducir valor", "Enter a numeric value.", "Introduzca un valor numérico.",
                "Enter at least one digit.", "Introduzca al menos un dígito.", "Clear", "Borrar");

            AddTo("it",
                "Menu", "Menu", "Stitching", "Cucitura", "Folding", "Piegatura", "Trimming", "Rifilatura", "Conveyor", "Convogliatore",
                "1. Menu", "1. Menu", "2. Stitching", "2. Cucitura", "3. Folding", "3. Piegatura", "4. Trimming", "4. Rifilatura", "5. Conveyor", "5. Convogliatore",
                "Overview and live machine preview.", "Panoramica e anteprima macchina in tempo reale.",
                "Configure stitching for this job.", "Configura la cucitura per questo lavoro.",
                "Configure folding for this job.", "Configura la piegatura per questo lavoro.",
                "Configure trimming for this job.", "Configura la rifilatura per questo lavoro.",
                "Configure the conveyor / output for this job.", "Configura il convogliatore / l’uscita per questo lavoro.",
                "Live Preview", "Anteprima in tempo reale", "Status: ", "Stato: ", "Machine: ", "Macchina: ", "Job: ", "Lavoro: ",
                "No job loaded", "Nessun lavoro caricato", "{0} pages", "{0} pagine",
                "Back", "Indietro", "Back: {0}", "Indietro: {0}", "Next: {0}", "Avanti: {0}",
                "Select a configuration step to reset its settings.", "Seleziona un passaggio di configurazione da ripristinare.",
                "{0} settings reset to defaults. Select Save to keep them.", "Le impostazioni di {0} sono state ripristinate. Seleziona Salva per mantenerle.",
                "Select a configuration step to save its settings.", "Seleziona un passaggio di configurazione da salvare.",
                "{0} configuration saved.", "Configurazione di {0} salvata.",
                "Paper Size (W x L)", "Formato carta (L x L)", "Stitch Mode", "Modalità cucitura", "Spacing", "Spaziatura",
                "Horizontal Offset", "Offset orizzontale", "Vertical Offset", "Offset verticale",
                "Stitching Parameters", "Parametri di cucitura", "Paper Width (W)", "Larghezza carta (L)", "Paper Length (L)", "Lunghezza carta (L)",
                "Saddle", "A sella", "Top", "Superiore", "Right Corner", "Angolo destro", "Left Corner", "Angolo sinistro", "None", "Nessuna",
                "Spacing Between Stitches", "Spaziatura tra i punti", "Horizontal Offset Stitch", "Offset orizzontale cucitura",
                "(Left -/ Right +)", "(Sinistra - / Destra +)", "Vertical Offset Stitch", "Offset verticale cucitura",
                "(Front - / Rear +)", "(Anteriore - / Posteriore +)", "No stitching", "Cucitura disattivata",
                "Set Paper Width", "Imposta larghezza carta", "Paper width ({0})", "Larghezza carta ({0})",
                "Enter the sheet width used by the stitching job.", "Inserisci la larghezza del foglio usata per la cucitura.",
                "Set Paper Length", "Imposta lunghezza carta", "Paper length ({0})", "Lunghezza carta ({0})",
                "Enter the sheet length used by the stitching job.", "Inserisci la lunghezza del foglio usata per la cucitura.",
                "Set Stitch Spacing", "Imposta spaziatura cucitura", "Spacing between stitches ({0})", "Spaziatura tra i punti ({0})",
                "Enter the distance between stitch positions.", "Inserisci la distanza tra le posizioni di cucitura.",
                "Set Horizontal Offset", "Imposta offset orizzontale", "Horizontal offset ({0})", "Offset orizzontale ({0})",
                "Use a negative value for left or a positive value for right.", "Usa un valore negativo per sinistra o positivo per destra.",
                "Set Vertical Offset", "Imposta offset verticale", "Vertical offset ({0})", "Offset verticale ({0})",
                "Use a negative value for front or a positive value for rear.", "Usa un valore negativo per anteriore o positivo per posteriore.",
                "Paper width", "Larghezza carta", "Paper length", "Lunghezza carta", "Stitch spacing", "Spaziatura cucitura",
                "Horizontal offset", "Offset orizzontale", "Vertical offset", "Offset verticale",
                "{0} updated to {1} {2}.", "{0} aggiornato a {1} {2}.",
                "Folding Settings", "Impostazioni di piegatura", "Fold Function:", "Funzione piegatura:", "Fold Position", "Posizione piega",
                "Backward (-)", "Indietro (-)", "Forward (+)", "Avanti (+)", "Adjust fold...", "Regola piega…",
                "Pressure Mode", "Modalità pressione", "Auto", "Auto", "Default", "Predefinito", "Manual", "Manuale",
                "Less pressure", "Meno pressione", "More pressure", "Più pressione",
                "Auto mode sets the clamp pressure automatically.", "La modalità Auto imposta automaticamente la pressione di serraggio.",
                "Fold offset (from center)", "Offset piega (dal centro)", "Fold direction", "Direzione piega",
                "Folding disabled", "Piegatura disattivata", "Set Fold Position", "Imposta posizione piega",
                "Fold position ({0})", "Posizione piega ({0})",
                "Enter a value from {0} (backward) to {1} (forward).", "Inserisci un valore da {0} (indietro) a {1} (avanti).",
                "Fold position", "Posizione piega",
                "Trimming Settings", "Impostazioni di rifilatura", "Trim Function:", "Funzione rifilatura:",
                "Final Booklet Length", "Lunghezza finale opuscolo", "Enter desired final length", "Inserisci la lunghezza finale desiderata",
                "Clamp Conveyor Height", "Altezza convogliatore di serraggio", "Automatic", "Automatico",
                "Maximum", "Massimo", "Minimum", "Minimo", "Chip Blower", "Soffiatore rifili",
                "On", "Acceso", "Off", "Spento", "Evacuates trim chips", "Evacua i rifili",
                "Set Final Booklet Length", "Imposta lunghezza finale opuscolo",
                "Final booklet length ({0})", "Lunghezza finale opuscolo ({0})",
                "Enter the desired finished length from {0} to {1}.", "Inserisci la lunghezza finale desiderata da {0} a {1}.",
                "Final booklet length", "Lunghezza finale opuscolo",
                "Conveyor Settings", "Impostazioni convogliatore", "Booklet Spacing", "Spaziatura opuscoli",
                "Booklet Offset", "Offset opuscoli", "Conveyor Full Detection", "Rilevamento convogliatore pieno",
                "1 = small space, 29 = long space, 30 = continuous advance", "1 = spazio ridotto, 29 = spazio ampio, 30 = avanzamento continuo",
                "Set Booklet Spacing", "Imposta spaziatura opuscoli", "Booklet spacing", "Spaziatura opuscoli",
                "Enter the output conveyor advance from 1 to 30.", "Inserisci l’avanzamento del convogliatore di uscita da 1 a 30.",
                "Set Booklet Offset", "Imposta offset opuscoli", "Booklet offset", "Offset opuscoli",
                "Enter how often a booklet should be offset, from 1 to 30.", "Inserisci ogni quanti opuscoli applicare l’offset, da 1 a 30.",
                "Enter a whole number from 1 to 30.", "Inserisci un numero intero da 1 a 30.",
                "{0} updated to {1}.", "{0} aggiornato a {1}.",
                "Use +/- for direction and . for fractional values.", "Usa +/- per la direzione e . per i decimali.",
                "Use the decimal key for fractional values.", "Usa il tasto decimale per i valori frazionari.",
                "Enter a value from {0} to {1}.", "Inserisci un valore da {0} a {1}.",
                "Enter Value", "Inserisci valore", "Enter a numeric value.", "Inserisci un valore numerico.",
                "Enter at least one digit.", "Inserisci almeno una cifra.", "Clear", "Cancella");

            AddTo("fr",
                "Reset", "Réinitialiser", "Save", "Enregistrer",
                "Adjust fold forward (+) or backward (-) from center", "Décalez le pli vers l’avant (+) ou l’arrière (-) depuis le centre",
                "Auto mode will adjust pressure based on booklet thickness", "Le mode Auto règle la pression selon l’épaisseur de la brochure",
                "Enter the desired final length", "Saisissez la longueur finale souhaitée",
                "Trimmer height conveyor self adjusts in relation to booklet thickness", "La hauteur du convoyeur de massicotage s’adapte à l’épaisseur de la brochure",
                "Adjust the output conveyor advance (1 to 30) to set the space between booklets", "Réglez l’avance du convoyeur de sortie (1 à 30) pour espacer les brochures",
                "Offset every X booklet to make counting easier", "Décalez chaque Xe brochure pour faciliter le comptage",
                "Choose whether to stop when the machine conveyor is full", "Choisissez d’arrêter ou non lorsque le convoyeur est plein");
            AddTo("nl",
                "Reset", "Herstellen", "Save", "Opslaan",
                "Adjust fold forward (+) or backward (-) from center", "Verschuif de vouw vooruit (+) of achteruit (-) vanaf het midden",
                "Auto mode will adjust pressure based on booklet thickness", "De automatische modus past de druk aan de boekdikte aan",
                "Enter the desired final length", "Voer de gewenste eindlengte in",
                "Trimmer height conveyor self adjusts in relation to booklet thickness", "De hoogte van de snijtransportband past zich aan de boekdikte aan",
                "Adjust the output conveyor advance (1 to 30) to set the space between booklets", "Stel de uitvoertransportstap (1 tot 30) in voor de afstand tussen boeken",
                "Offset every X booklet to make counting easier", "Verschuif elk Xe boek om tellen eenvoudiger te maken",
                "Choose whether to stop when the machine conveyor is full", "Kies of de machine stopt wanneer de transportband vol is");
            AddTo("de",
                "Reset", "Zurücksetzen", "Save", "Speichern",
                "Adjust fold forward (+) or backward (-) from center", "Falz ab Mitte vorwärts (+) oder rückwärts (-) verschieben",
                "Auto mode will adjust pressure based on booklet thickness", "Der Automatikmodus passt den Druck an die Broschürendicke an",
                "Enter the desired final length", "Gewünschte Endlänge eingeben",
                "Trimmer height conveyor self adjusts in relation to booklet thickness", "Die Höhe des Schneidförderers passt sich an die Broschürendicke an",
                "Adjust the output conveyor advance (1 to 30) to set the space between booklets", "Auslagevorschub (1 bis 30) für den Broschürenabstand einstellen",
                "Offset every X booklet to make counting easier", "Jede X. Broschüre versetzen, um das Zählen zu erleichtern",
                "Choose whether to stop when the machine conveyor is full", "Wählen Sie, ob bei voller Auslage gestoppt wird");
            AddTo("es",
                "Reset", "Restablecer", "Save", "Guardar",
                "Adjust fold forward (+) or backward (-) from center", "Ajuste el pliegue adelante (+) o atrás (-) desde el centro",
                "Auto mode will adjust pressure based on booklet thickness", "El modo automático ajusta la presión según el grosor del folleto",
                "Enter the desired final length", "Introduzca la longitud final deseada",
                "Trimmer height conveyor self adjusts in relation to booklet thickness", "La altura del transportador de corte se adapta al grosor del folleto",
                "Adjust the output conveyor advance (1 to 30) to set the space between booklets", "Ajuste el avance del transportador (1 a 30) para separar los folletos",
                "Offset every X booklet to make counting easier", "Desplace cada X folletos para facilitar el conteo",
                "Choose whether to stop when the machine conveyor is full", "Elija si debe detenerse cuando el transportador esté lleno");
            AddTo("it",
                "Reset", "Ripristina", "Save", "Salva",
                "Adjust fold forward (+) or backward (-) from center", "Regola la piega avanti (+) o indietro (-) rispetto al centro",
                "Auto mode will adjust pressure based on booklet thickness", "La modalità Auto regola la pressione in base allo spessore dell’opuscolo",
                "Enter the desired final length", "Inserisci la lunghezza finale desiderata",
                "Trimmer height conveyor self adjusts in relation to booklet thickness", "L’altezza del convogliatore di rifilatura si adatta allo spessore dell’opuscolo",
                "Adjust the output conveyor advance (1 to 30) to set the space between booklets", "Regola l’avanzamento del convogliatore (da 1 a 30) per spaziare gli opuscoli",
                "Offset every X booklet to make counting easier", "Sfalsa ogni X opuscoli per facilitare il conteggio",
                "Choose whether to stop when the machine conveyor is full", "Scegli se fermare la macchina quando il convogliatore è pieno");
            AddTo("fr",
                "Horizontal Offset Stitch ", "Décalage horizontal des agrafes ",
                "Vertical Offset Stitch ", "Décalage vertical des agrafes ",
                "[Job Name]", "[Nom du travail]",
                "Enter a value between -999,999.999 and 999,999.999.", "Saisissez une valeur entre -999 999,999 et 999 999,999.",
                "Enter a non-negative whole number.", "Saisissez un nombre entier positif ou nul.",
                "The maximum value is 999,999,999.", "La valeur maximale est 999 999 999.");
            AddTo("nl",
                "Horizontal Offset Stitch ", "Horizontale nietverschuiving ",
                "Vertical Offset Stitch ", "Verticale nietverschuiving ",
                "[Job Name]", "[Taaknaam]",
                "Enter a value between -999,999.999 and 999,999.999.", "Voer een waarde in tussen -999.999,999 en 999.999,999.",
                "Enter a non-negative whole number.", "Voer een niet-negatief geheel getal in.",
                "The maximum value is 999,999,999.", "De maximumwaarde is 999.999.999.");
            AddTo("de",
                "Horizontal Offset Stitch ", "Horizontaler Heftversatz ",
                "Vertical Offset Stitch ", "Vertikaler Heftversatz ",
                "[Job Name]", "[Auftragsname]",
                "Enter a value between -999,999.999 and 999,999.999.", "Geben Sie einen Wert zwischen -999.999,999 und 999.999,999 ein.",
                "Enter a non-negative whole number.", "Geben Sie eine nicht negative ganze Zahl ein.",
                "The maximum value is 999,999,999.", "Der Höchstwert ist 999.999.999.");
            AddTo("es",
                "Horizontal Offset Stitch ", "Desplazamiento horizontal de grapas ",
                "Vertical Offset Stitch ", "Desplazamiento vertical de grapas ",
                "[Job Name]", "[Nombre del trabajo]",
                "Enter a value between -999,999.999 and 999,999.999.", "Introduzca un valor entre -999.999,999 y 999.999,999.",
                "Enter a non-negative whole number.", "Introduzca un número entero no negativo.",
                "The maximum value is 999,999,999.", "El valor máximo es 999.999.999.");
            AddTo("it",
                "Horizontal Offset Stitch ", "Offset orizzontale cucitura ",
                "Vertical Offset Stitch ", "Offset verticale cucitura ",
                "[Job Name]", "[Nome lavoro]",
                "Enter a value between -999,999.999 and 999,999.999.", "Inserisci un valore compreso tra -999.999,999 e 999.999,999.",
                "Enter a non-negative whole number.", "Inserisci un numero intero non negativo.",
                "The maximum value is 999,999,999.", "Il valore massimo è 999.999.999.");
        }
    }
}
